[package]
name = "runtime"
version = "1.0.0"
edition.workspace = true

[features]
testing = []

[dependencies]
anyhow.workspace = true
cairo-lang-runner.workspace = true
cairo-lang-casm.workspace = true
cairo-lang-utils.workspace = true
cairo-lang-starknet.workspace = true
cairo-felt.workspace = true
starknet_api.workspace = true
starknet.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
blockifier.workspace = true
cairo-vm = "0.8.1"
serde_json.workspace = true
serde.workspace = true
flatten-serde-json = "0.1.0"
cheatnet = { path = "../cheatnet" }
conversions = { path = "../conversions" }
scarb-artifacts = { path = "../scarb-artifacts" }
k256 = { version = "0.13.2", features = ["sha256", "ecdsa", "serde"] }
p256 = { version = "0.13.2", features = ["sha256", "ecdsa", "serde"] }

[lib]
name = "runtime"
