[package]
name = "map3"
version = "0.1.0"
edition = "2024_07"

[[target.starknet-contract]]
sierra = true

[[target.lib]]
sierra = false

[dependencies]
snforge_std = { path = "../../../snforge_std" }
starknet = "2.8.5"

[scripts]
test = "snforge test"
