[package]
name = "using_cheatcodes_cancelling_cheat"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.7.0"
assert_macros = "2.7.0"

[dev-dependencies]
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
