[package]
name = "snforge_std_deprecated"
version = "0.49.0"
edition = "2024_07"
description = "Cairo testing library"
documentation = "https://foundry-rs.github.io/starknet-foundry/appendix/snforge-library.html"
repository = "https://github.com/foundry-rs/starknet-foundry"
license-file = "../LICENSE"
re-export-cairo-plugins = ["snforge_scarb_plugin_deprecated"]
cairo-version = "<=2.11.4"

[dependencies]
snforge_scarb_plugin_deprecated = { path = "../crates/snforge-scarb-plugin-deprecated" }
