[package]
name = "configuration"
version = "1.0.0"
edition.workspace = true

[features]
testing = []

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
serde.workspace = true
camino.workspace = true
toml.workspace = true
tempfile.workspace = true


