[package]
name = "fibonacci"
version.workspace = true
edition = "2024_07"

[scripts]
test.workspace = true

[tool]
snforge.workspace = true

[dependencies]
addition = { path = "../addition" }
starknet = "2.7.0"

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["addition::AdditionContract"]

[lib]
