[package]
name = "snforge_scarb_plugin"
version.workspace = true
edition = "2021"
publish = false
rust-version = "1.80.1"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
cairo-lang-macro.workspace = true
cairo-lang-parser.workspace = true
cairo-lang-utils.workspace = true
cairo-lang-syntax.workspace = true
url.workspace = true
indoc.workspace = true
smol_str.workspace = true
num-bigint.workspace = true

[dev-dependencies]
lazy_static.workspace = true
regex.workspace = true
