[package]
name = "snforge-scarb-plugin"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
cairo-lang-macro = { git = "https://github.com/software-mansion/scarb", rev = "327bd6b"}

cairo-lang-parser.workspace = true
cairo-lang-utils.workspace = true
cairo-lang-syntax.workspace = true
cairo-lang-diagnostics.workspace = true
cairo-lang-filesystem.workspace = true
cairo-lang-sierra.workspace = true

url.workspace = true
indoc.workspace = true
serde_json.workspace = true
scarb-api = { path = "../scarb-api" }
smol_str = "0.2.1"
