[package]
name = "direct_storage_access"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.7.0"
assert_macros = "2.8.2"

[dev-dependencies]
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
