[package]
name = "cast"
description = "Cast - a Starknet Foundry CLI client"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.71"
camino = "1.1.4"
clap = { version = "4.3.0", features = ["derive"] }
console = "0.15.7"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
starknet = "0.4.0"
tokio = { version = "1.28.2", features = ["full"] }
url = "2.2.2"
rand = "0.8.5"
primitive-types = "0.12.1"
shellexpand = "3.1.0"
toml = "0.5.2"
project-root = "0.2.2"
scarb-metadata_1_4_2.workspace = true
which = "4.4.0"

[dev-dependencies]
ctor.workspace = true
snapbox = "0.4.11"
indoc.workspace = true
url = "2.4.0"
reqwest = "0.11.18"
tempfile = "3.3.0"
test-case = "3.1.0"
fs_extra = "1.3.0"
sealed_test = "1.0.0"

[[bin]]
name = "sncast"
path = "src/main.rs"
