[package]
name = "ignoring_example"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.5"

[dev-dependencies]
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
