[package]
name = "testing_contract_internals"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.7.0"

[dev-dependencies]
sncast_std.workspace = { path = "../../snforge_std" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
