[package]
name = "deploy"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.5"
sncast_std = { path = "../../../sncast_std" }

[dev-dependencies]
snforge_std = { path = "../../../snforge_std" }

[[target.lib]]
sierra = true

[scripts]
test = "snforge test"
