[workspace]
members = [
    "crates/*",
]

[workspace.scripts]
test = "snforge"

[workspace.tool.snforge]

[workspace.package]
version = "0.1.0"

[package]
name = "hello_workspaces"
version.workspace = true
edition = "2024_07"

[scripts]
test.workspace = true

[tool]
snforge.workspace = true

[dependencies]
fibonacci = { path = "crates/fibonacci" }
addition = { path = "crates/addition" }
starknet = "2.7.0"

[dev-dependencies]
snforge_std.workspace = true

[workspace.dependencies]
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true
