name: Publish snforge_scarb_plugin

on:
  workflow_dispatch:
    inputs:
      prod_registry:
        required: false
        type: boolean
      # Specify the version in MAJOR.MINOR.PATCH format, without a leading 'v'
      overridden_plugin_version:
        required: false
        type: string
      plugin_name:
        required: true
        default: "snforge-scarb-plugin"
        type: string

jobs:
  build-binaries:
    name: Build Plugin Binaries
    uses: ./.github/workflows/_build-plugin-binaries.yml
    with:
      overridden_plugin_version: ${{ inputs.overridden_plugin_version != '' && inputs.overridden_plugin_version || '' }}
      plugin_name: ${{ inputs.plugin_name }}
  
  publish-plugin:
    name: Publish Plugin
    needs: build-binaries
    uses: ./.github/workflows/_publish-plugin.yml
    with:
      prod_registry: ${{ inputs.prod_registry }}
      overridden_plugin_version: ${{ inputs.overridden_plugin_version != '' && inputs.overridden_plugin_version || '' }}
      plugin_name: '${{ inputs.plugin_name }}'
    secrets: inherit
